# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4efde92971f8ca87c51b546a57f3aa275fa349023c942dc9175d8d049cacd09450922d4690095919de43fba25dfeae8138e2af5fa6cc318d0100f1cfc190fd16

test:
  secret_key_base: 3ff0e1b20f2981ce375ce758abd7efb20971702f37eb9153f66a446ef16c9744db3c553591b9e61dae7a3b12be1284b0df9dc2edbf4d0e4500e8b39e993e42e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
